language: python
sudo: false

env:
  - LUA="lua 5.2"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA # install all stuff into ./lua_install
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  #- luarocks make --local
  - luacheck --std max+busted lib/*.lua
  - cd $TRAVIS_BUILD_DIR/lib && busted --verbose --coverage .

after_success:
  - cd $TRAVIS_BUILD_DIR/lib && luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install
